### ISSUE TITLE
Customs Clearance Detail is required (Error code: 2449)

### ISSUE THREAD

**Issue by djangochamp** [python-fedex-devs/python-fedex#85]
Hello,
I am getting this error while using shipping service. Both addresses that I used as a sender and recipient are from same country(India).
Thanks in Advance

**Comment by gvyshnya** [comment]
The change for International Shipment is proposed as a pull request now. It has yet to be approved by the code owner before it goes to the trunk code of the library. Once/If it is approved, you can then use the new capabilities.

**Comment by djangochamp** [comment]
I am getting this error in domestic shipment. Both addresses that I am using are from same country.

**Comment by gvyshnya** [comment]
@djangochamp : this is expected behaviour of Fedex API - it treats everything that happens outside the US as international transactions (even though in fact it happens within the same foreign country - India, in your case). 

Therefore the current version of the library will generate the error you reported. 

Please be patient and watch my pull request per https://github.com/python-fedex-devs/python-fedex/pull/84 - once it is approved/integrated, the library will start supporting international transactions over Fedex.

**Comment by gvyshnya** [comment]
Updated pull request per https://github.com/python-fedex-devs/python-fedex/pull/86 submitted to enable support for international shipments
