### ISSUE TITLE
This tracking number cannot be found. (Error Code: 9040)

### ISSUE THREAD

**Issue by flyysoul** [python-fedex-devs/python-fedex#87]
Hello,
I was using track service with right tracking_number.Request was successfully processed.But I got an error code :9040;
And the DeliveryOptionEligibilityDetails in response is like this:
```
(DeliveryOptionEligibilityDetail){
   Option = "REDIRECT_TO_HOLD_AT_LOCATION"
   Eligibility = "INELIGIBLE"
```
Is it mean that some problems in my `CONFIG_OBJ`?
Thanks a lot

**Comment by alxpck** [comment]
Hi, 

I had the same issue. It turns out FedEx won't let you track a package using test credentials. You have to switch to the production server and use production credentials. 

You can get your production credentials here: https://www.fedex.com/us/developer/web-services/process.html?tab=tab4#tab4

Once I moved to production it started working for me. 

Hope this helps!

**Comment by flyysoul** [comment]
@alxpck Thinks ,it`s useful

**Comment by radzhome** [comment]
+1

**Comment by yan1990y** [comment]
I had the same issue.I had prodcution key,I can get rate info.In c# demo,the key works,but in python-fedex I meet the problem.

**Comment by yan1990y** [comment]
I just solved the problem.
self.SelectionDetails.CarrierCode = 'FDXG'
the value must change for your location.I guess G means globle
